name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-BAR-2-1-chocolatine-pierre.godin-launay.git" # change to epitech repo
  EXECUTABLES: "a.out"  

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: check
        run: |
          rm -f coding-style-reports.log
          check.sh $(pwd) $(pwd)
          cat coding-style-reports.log
      - name: coding style
        run: |
          IFS=
          while IFS= read -r line; do
            error="$(echo $line | cut -d ' ' -f 2)"
            file="$(echo $line | cut -d ' ' -f 1)"
            severity="$(echo $error | cut -d ':' -f 1)"
            code="$(echo $error | cut -d ':' -f 2)"
            line="$(echo $file | cut -d ':' -f 2)"
            filename="$(echo $file | cut -d ':' -f 1)"
            echo "::error file=$filename,line=$line,title=$severity coding style error: $filename::$code"
          done < coding-style-reports.log
          if [[ "$(du -b coding-style-reports.log | cut -d ' ' -f 1)" != "0" ]]; then
            echo ::exit::failure
          fi

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make
        timeout-minutes: 2
        run: make 
      - name: Make clean
        run: |
          make clean
          for executable in ${{ env.EXECUTABLES }}; do
            if [[ ! -f "$executable" || ! -x "$executable" ]]; then
              echo ::exit::failure
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    timeout-minutes: 2
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make
        run: make tests_run

  mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          