name: Memory Leak Check

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_memory_leaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make
        timeout-minutes: 2
        run: make
      - name: List files
        run: ls -l
      - name: Ensure Executable Permissions
        run: chmod +x ./program
      - name: install valgrind
        run: sudo apt install valgrind -y
      - name: Run Valgrind
      - name:
        run: valgrind ./program > valgrind_output.log
        run: |
          if grep -q -F "ERROR SUMMARY: 0 errors from 0 contexts" valgrind_output.log; then
            echo "No valgrind error"
          else
            echo "valgrind error"
            exit 1
          fi

      - name:
        run: make clean