name: Memory Leak Check

on:
  push:
  pull_request:

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential valgrind

      - name: Compile repository
        run: make

      - name: Run code w/ valgrind
        run: |
          valgrind ./program > valgrind_output.log

      - name: Check valgrind
        run: |
          if grep -q -F "ERROR SUMMARY: 0 errors from 0 contexts" "valgrind_output.log"; then
            echo 'No valgrind error'
          else
            echo 'Valgrind error'
            exit 1
          fi

      - name: Clean repository
        run: make clean