name: Memory Leak Check

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_memory_leaks:
    runs-on: windows-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make
        timeout-minutes: 2
        run: make
      - name: List files
        run: ls -l
      - name: Ensure Executable Permissions
        run: chmod +x ./program.exe
      - name: Run Valgrind
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./program.exe | tee valgrind_output.log
          if grep -q "ERROR SUMMARY: 0 errors from 0 contexts" valgrind_output.log; then
            echo "No memory leaks detected."
          else
            echo "::error file=valgrind_output.log::Memory leaks detected."
            exit 1
          fi