name: mirroring

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2028/B-DOP-200-BAR-2-1-chocolatine-pierre.godin-launay.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            